name: Periodic health check

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-18.04
    steps:
    - name: ping
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://appdev-pokedex.herokuapp.com
        max-attempts: 3
        retry-delay: 5s